### PR TITLE
#186: Exporter's filename validations

### LINKED ISSUE #186: Export_image crashes on unwritable filename
Using the [exporter](https://github.com/TokisanGames/Terrain3D/wiki/Importing-&-Exporting-Data#exporting-data), entering a name like 'color.png' will crash, presumably unable to write to c:\color.png. Entering `res://color.png` works fine.

Try testing the file and see if it's writable, and printing an error message if not. The validation needs to be in export_image in C++, not in gdscript.

If no path is specified, and it's just a filename, preface the filename with `res://` so it goes in the project folder.

Test the pr against a set of invalid paths and filenames including:
* writing to read-only permission areas (c:\\ or / on linux)
* invalid filenames (color*.png, color".png, )
* a file that exists and is writable
* a file that exists and is marked readonly by the operating system

See https://docs.godotengine.org/en/stable/classes/class_fileaccess.html
https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html

### PR DESCRIPTION
**Pull request by rds1983**
This PR adds 3 checks for the exporter filename:
1. The filename doesnt contain invalid characters.
2. The file can be opened for writing.
3. Prepends "res://" if the filename is simple(it doesnt contain folder delimiter or ':' characters).

Fixes #186

### CODE REVIEW

File: src/terrain_3d_storage.cpp [hunk 1]
```diff
@@ -853,11 +853,56 @@ Error Terrain3DStorage::export_image(String p_file_name, MapType p_map_type) {
...
+
 	if (get_region_count() == 0) {
 		LOG(ERROR, "No valid regions. Nothing to export");
 		return FAILED;
 	}
 
+	// Simple file name validation
+	static String bad_chars = "!@%^*~|\"";
+	for (int i = 0; i < bad_chars.length(); ++i)
+	{
```
Comment (TokisanGames) [inline src/terrain_3d_storage.cpp:865]: I'm going to make changes so I can get this merged in. In the future, please format with braces on the same line. See formatting in https://github.com/TokisanGames/Terrain3D/blob/0.9/CONTRIBUTING.md.

**Comment by TokisanGames** [comment]
Ok, looks good. I added some other updates that needed to be made.
