### PR TITLE
fix mouse_picking when compositor in use

### LINKED ISSUE #595: heightmap painting only works partially if there is a compositor effect
### Terrain3D version

v0.9.3a

### System information

Godot v4.3.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Laptop GPU (NVIDIA; 32.0.15.6636) - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 Threads)

### Is the issue reproducable in the demo?

Yes

### Issue description

When there is a compositor effect assigned to the environment node, painting doesn't work correctly anymore. The circular shape gets stuck and is unresponsive. 

I used PPMagic(https://github.com/peterprickarz/PPMagic) for testing, as well as my own compositor effect.

I have a mrp, but it seems i cannot upload it here. 

### Logs

_No response_

### PR DESCRIPTION
**Pull request by Xtarsia**
fixes #595 by adding an empty compositor to _mouse_cam

### CODE REVIEW

**Comment by TokisanGames** [comment]
@nan0m Please test this build and confirm it fixes your issue. Checks/build all/artifact

**Comment by nan0m** [comment]
I can confirm it fixes the issue. Thank you!

File: src/terrain_3d.cpp [hunk 1]
```diff
@@ -16,6 +16,7 @@
 #include <godot_cpp/classes/viewport.hpp>
 #include <godot_cpp/classes/viewport_texture.hpp>
 #include <godot_cpp/classes/world3d.hpp>
+#include <godot_cpp/classes/compositor.hpp>
```
Comment (TokisanGames) [inline src/terrain_3d.cpp:19]: @Xtarsia Are you using [clang-format](https://terrain3d.readthedocs.io/en/latest/docs/contributing.html#install-clang-format)? It should have sorted this list alphabetically when you attempted to commit.

Comment (Xtarsia) [reply src/terrain_3d.cpp:19]: Ah.. I think I reset my repo and forgot to run the script again for that.

**Comment by TokisanGames** [comment]
Thank you
