### PR TITLE
Fix RID leaks

### LINKED ISSUE #663: Many leaked RIDs on close
### Terrain3D version

1.0 stable

### System information

Godot v4.4.1.stable unknown - EndeavourOS #1 ZEN SMP PREEMPT_DYNAMIC Sun, 23 Mar 2025 17:17:17 +0000 on Wayland - X11 display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (nvidia; 570.133.07) - AMD Ryzen 5 5600H with Radeon Graphics (12 threads)

### Is the issue reproducable in the demo?

Yes

### Issue description

Closing my game takes a few seconds usually and always prints a bunch of leaked RID allocations. I narrowed it down to Terrain3D and it also happens in a fresh download of the addon with the demo.
Luckily, it seems to run fine, it's just concerning seeing these every time and having a simple terrain cause this many leaks, especially if I add more and more detail to my terrain.
These logs are straight from the demo, on the latest version I downloaded moments before running it:

```
Godot Engine v4.4.1.stable.official.49a5bc7b6 - https://godotengine.org
Vulkan 1.4.303 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce GTX 1650

ERROR: 2 RID allocations of type 'N10RendererRD12LightStorage11ShadowAtlasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N10RendererRD12LightStorage15ReflectionAtlasE' were leaked at exit.
ERROR: 2 RID allocations of type 'N10RendererRD12LightStorage13LightInstanceE' were leaked at exit.
ERROR: 2 RID allocations of type 'N10RendererRD12LightStorage5LightE' were leaked at exit.
ERROR: 1 RID allocations of type 'N10RendererRD15MaterialStorage8MaterialE' were leaked at exit.
ERROR: 1 RID allocations of type 'N10RendererRD14TextureStorage12RenderTargetE' were leaked at exit.
ERROR: 3 RID allocations of type 'N10RendererRD14TextureStorage7TextureE' were leaked at exit.
ERROR: 1 RID allocations of type 'N16RendererViewport8ViewportE' were leaked at exit.
ERROR: 3 RID allocations of type 'N17RendererSceneCull8InstanceE' were leaked at exit.
ERROR: 1 RID allocations of type 'N17RendererSceneCull8ScenarioE' were leaked at exit.
ERROR: 1 RID allocations of type 'N17RendererSceneCull6CameraE' were leaked at exit.
WARNING: 7 RIDs of type "Texture" were leaked.
     at: finalize (servers/rendering/rendering_device.cpp:7130)
```

### Logs

_No response_

### PR DESCRIPTION
**Pull request by TokisanGames**
Fixes #663 

Cleaned up RID leaks in:
* Assets
* Material

Tested in the demo and OOTA w/ multiple scenes.

There are UI CanvasItems leaked in the editor, but I don't care about them. The UI needs an overhaul anyway and those can be looked at in the future.

```
WARNING: 3 RIDs of type "CanvasItem" were leaked.
   at: _free_rids (servers/rendering/renderer_canvas_cull.cpp:2679)
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
   at: cleanup (core/object/object.cpp:2378)
ERROR: Cannot get path of node as it is not in a scene tree.
   at: get_path (scene/main/node.cpp:2345)
Leaked instance: TextureButton:2350219611833 - Node path:
Leaked instance: Object:2350236389050
ERROR: Cannot get path of node as it is not in a scene tree.
   at: get_path (scene/main/node.cpp:2345)
Leaked instance: TextureButton:2350504824522 - Node path:
Leaked instance: Object:2350521601739
ERROR: Cannot get path of node as it is not in a scene tree.
   at: get_path (scene/main/node.cpp:2345)
Leaked instance: TextureButton:2350790037211 - Node path:
Leaked instance: Object:2350806814428
Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not freed (with `free()` or `queue_free()`).

```

### CODE REVIEW

File: src/terrain_3d_material.cpp [hunk 1]
```diff
@@ -568,7 +568,9 @@ void Terrain3DMaterial::initialize(Terrain3D *p_terrain) {
 	}
 	LOG(INFO, "Initializing material");
 	_preload_shaders();
-	_material = RS->material_create();
+	if (!_material.is_valid()) {
+		_material = RS->material_create();
+	}
```
Comment (TokisanGames) [inline src/terrain_3d_material.cpp:573]: Strangely, in OOTA when loading a scene, but not the whole game, my Terrain3D starts with _material as the same RID as in the editor. This reuses it if already valid, though it could clear it instead, but that might have an issue in the editor.
I don't have any code that instantiates Terrain3D, only scenes with Terrain3D inside. Materials aren't duplicated. The material is saved to disk.
I couldn't reproduce it in the demo, not with saved or internal materials, nor with pre-attached or script loaded scenes. Scene or game, the demo always began with a cleared _material.

**Review by Xtarsia — APPROVED** [review]
Tested, same results with the texture buttons. Are those the channel packer buttons i wonder?
