### PR TITLE
Fix #705 - free_editor_textures doesn't work w/ local assets

### LINKED ISSUE #705: Free editor textures w/ scene saved assets
### Description

`Free_editor_textures` doesn't reload if `assets` is saved in the scene

### PR DESCRIPTION
**Pull request by TokisanGames**
* Fixes error by skipipng free_editor_textures with a local Assets.
* Warn to change one if both are set

Fixes #705

### CODE REVIEW

File: src/terrain_3d.cpp [hunk 1]
```diff
@@ -866,8 +865,12 @@ void Terrain3D::_notification(const int p_what) {
 			// Node is ready
 			LOG(INFO, "NOTIFICATION_READY");
 			if (_free_editor_textures && !IS_EDITOR && _assets.is_valid()) {
-				LOG(INFO, "free_editor_textures enabled, clearing texture assets");
-				_assets->clear_textures();
+				if (_assets->get_path().contains("Terrain3DAssets")) {
+					LOG(WARN, "free_editor_textures requires `Assets` be saved to a file. Do so, or disable FET to turn off this warning");
```
Comment (Xtarsia) [inline src/terrain_3d.cpp]: "free_editor_textures requires `Assets` be saved to a file. Do so, or disable free_editor_textures to turn off this warning"

FET seems a bit overkill here to me.
