### PR TITLE
Fixes for C# bindings 

### LINKED ISSUE #672: Potential misuse of the GDE binding API
### Terrain3D version

v1.0.0 stable

### System information

Godot v4.4.stable.mono - Windows 10 (build 19044) - Multi-window, 4 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti (NVIDIA; 32.0.15.7283) - AMD Ryzen 9 5900X 12-Core Processor (24 threads)

### Is the issue reproducable in the demo?

Not applicable

### Issue description

Hello, thanks for the great work on the Terrain3D.

I'm the author of the [C# binding generator for GDExtensions](https://github.com/Delsin-Yu/CSharp-Wrapper-Generator-for-GDExtension) project. We have users [reporting that they are facing trouble generating C# bindings from this extension](https://github.com/Delsin-Yu/CSharp-Wrapper-Generator-for-GDExtension/issues/33).

After further investigation, we found several places where the current GDExtension system is struggling. While we have patched our binding generator to take a workaround, we believe it might be worth reporting to the original repository.

1. `Terrain3d::debug_level` is referencing a non-registered enum
```cpp
ADD_PROPERTY(PropertyInfo(Variant::INT, "debug_level", PROPERTY_HINT_ENUM, "Errors,Info,Debug,Extreme"), "set_debug_level", "get_debug_level");
```

2. Several places in the source code are passing `unsupported format character` (this error string literally comes from the `hint_string` entry when obtaining the class definition dictionary from the `ClassDb`).
```cpp
// Original C++ source code from Terrain3D
// The Godot is capable to recognize this type and use it for GDScript, but this hint string becomes `unsupported format character` when obtaining the class definition from `ClassDb`
ADD_PROPERTY(PropertyInfo(Variant::ARRAY, "mesh_list", PROPERTY_HINT_ARRAY_TYPE, vformat("%tex_size/%tex_size:%tex_size", Variant::OBJECT, PROPERTY_HINT_RESOURCE_TYPE, "Terrain3DMeshAsset"), ro_flags), "set_mesh_list", "get_mesh_list");
```

3. Several places in the source code are passing multi-typed type string, which led Godot to fall back into their common base type
```cpp
// Original C++ source code from Terrain3D
// Godot actually uses `Material` for this case
ADD_PROPERTY(PropertyInfo(Variant::OBJECT, "material_overlay", PROPERTY_HINT_RESOURCE_TYPE, "BaseMaterial3D,ShaderMaterial"), "set_material_overlay", "get_material_overlay");
```

### Logs

N/A

### PR DESCRIPTION
**Pull request by TokisanGames**
Fixes #672 

* Register debug_level enum
* Remove vformatted property hints
* Fix luminance_to_height default val

### CODE REVIEW

File: src/terrain_3d_assets.cpp [hunk 1]
```diff
@@ -667,8 +667,8 @@ void Terrain3DAssets::_bind_methods() {
 	ClassDB::bind_method(D_METHOD("save", "path"), &Terrain3DAssets::save, DEFVAL(""));
 
 	int ro_flags = PROPERTY_USAGE_STORAGE | PROPERTY_USAGE_EDITOR | PROPERTY_USAGE_READ_ONLY;
-	ADD_PROPERTY(PropertyInfo(Variant::ARRAY, "mesh_list", PROPERTY_HINT_ARRAY_TYPE, vformat("%tex_size/%tex_size:%tex_size", Variant::OBJECT, PROPERTY_HINT_RESOURCE_TYPE, "Terrain3DMeshAsset"), ro_flags), "set_mesh_list", "get_mesh_list");
-	ADD_PROPERTY(PropertyInfo(Variant::ARRAY, "texture_list", PROPERTY_HINT_ARRAY_TYPE, vformat("%tex_size/%tex_size:%tex_size", Variant::OBJECT, PROPERTY_HINT_RESOURCE_TYPE, "Terrain3DTextureAsset"), ro_flags), "set_texture_list", "get_texture_list");
+	ADD_PROPERTY(PropertyInfo(Variant::ARRAY, "mesh_list", PROPERTY_HINT_ARRAY_TYPE, "", ro_flags), "set_mesh_list", "get_mesh_list");
+	ADD_PROPERTY(PropertyInfo(Variant::ARRAY, "texture_list", PROPERTY_HINT_ARRAY_TYPE, "", ro_flags), "set_texture_list", "get_texture_list");
```
Comment (Delsin-Yu) [inline src/terrain_3d_assets.cpp:671]: The class db still requires the type name to function correctly.

```suggestion
	ADD_PROPERTY(PropertyInfo(Variant::ARRAY, "mesh_list", PROPERTY_HINT_ARRAY_TYPE, "Terrain3DMeshAsset", ro_flags), "set_mesh_list", "get_mesh_list");
	ADD_PROPERTY(PropertyInfo(Variant::ARRAY, "texture_list", PROPERTY_HINT_ARRAY_TYPE, "Terrain3DTextureAsset", ro_flags), "set_texture_list", "get_texture_list");
```

File: src/terrain_3d_data.cpp [hunk 2]
```diff
@@ -1216,10 +1216,10 @@ void Terrain3DData::_bind_methods() {
...
-	ADD_PROPERTY(PropertyInfo(Variant::ARRAY, "height_maps", PROPERTY_HINT_ARRAY_TYPE, vformat("%tex_size/%tex_size:%tex_size", Variant::OBJECT, PROPERTY_HINT_RESOURCE_TYPE, "Image"), ro_flags), "", "get_height_maps");
-	ADD_PROPERTY(PropertyInfo(Variant::ARRAY, "control_maps", PROPERTY_HINT_ARRAY_TYPE, vformat("%tex_size/%tex_size:%tex_size", Variant::OBJECT, PROPERTY_HINT_RESOURCE_TYPE, "Image"), ro_flags), "", "get_control_maps");
-	ADD_PROPERTY(PropertyInfo(Variant::ARRAY, "color_maps", PROPERTY_HINT_ARRAY_TYPE, vformat("%tex_size/%tex_size:%tex_size", Variant::OBJECT, PROPERTY_HINT_RESOURCE_TYPE, "Image"), ro_flags), "", "get_color_maps");
+	ADD_PROPERTY(PropertyInfo(Variant::ARRAY, "region_locations", PROPERTY_HINT_ARRAY_TYPE, "", ro_flags), "set_region_locations", "get_region_locations");
+	ADD_PROPERTY(PropertyInfo(Variant::ARRAY, "height_maps", PROPERTY_HINT_ARRAY_TYPE, "", ro_flags), "", "get_height_maps");
+	ADD_PROPERTY(PropertyInfo(Variant::ARRAY, "control_maps", PROPERTY_HINT_ARRAY_TYPE, "", ro_flags), "", "get_control_maps");
+	ADD_PROPERTY(PropertyInfo(Variant::ARRAY, "color_maps", PROPERTY_HINT_ARRAY_TYPE, "", ro_flags), "", "get_color_maps");
```
Comment (Delsin-Yu) [inline src/terrain_3d_data.cpp:1222]: Same here

```suggestion
	ADD_PROPERTY(PropertyInfo(Variant::ARRAY, "region_locations", PROPERTY_HINT_ARRAY_TYPE, "Vector2", ro_flags), "set_region_locations", "get_region_locations");
	ADD_PROPERTY(PropertyInfo(Variant::ARRAY, "height_maps", PROPERTY_HINT_ARRAY_TYPE, "Image", ro_flags), "", "get_height_maps");
	ADD_PROPERTY(PropertyInfo(Variant::ARRAY, "control_maps", PROPERTY_HINT_ARRAY_TYPE, "Image", ro_flags), "", "get_control_maps");
	ADD_PROPERTY(PropertyInfo(Variant::ARRAY, "color_maps", PROPERTY_HINT_ARRAY_TYPE, "Image", ro_flags), "", "get_color_maps");
```

**Review by Delsin-Yu — COMMENTED** [review]
I think we still need to provide the type name at least.

File: src/terrain_3d_assets.cpp (hunk 1 above)
Comment (TokisanGames) [reply src/terrain_3d_assets.cpp:671]: For documentation, the engine code shows this, and class name is at the end.

```	PropertyInfo(Variant::Type p_type, const StringName &p_name, PropertyHint p_hint = PROPERTY_HINT_NONE, const String &p_hint_string = "", uint32_t p_usage = PROPERTY_USAGE_DEFAULT, const StringName &p_class_name = "") :
			type(p_type),
			name(p_name),
			hint(p_hint),
			hint_string(p_hint_string),
			usage(p_usage) {
		if (hint == PROPERTY_HINT_RESOURCE_TYPE) {
			class_name = hint_string;
		} else {
			class_name = p_class_name;
		}
```

Because these are resources, hint is assigned to class.

**Comment by TokisanGames** [comment]
Alright, I have committed the suggestions and fixed luminance_to_height. Please let me know if you have any other suggestions or things that need work. Thanks.

**Comment by Delsin-Yu** [comment]
> Alright, I have committed the suggestions and fixed luminance_to_height. Please let me know if you have any other suggestions or things that need work. Thanks.

I'm still in the middle of rewriting my whole GDExtension binding generator to support auto-reporting more issues, but so far, I can't find any more. Thanks for supporting the C# development community.

**Comment by TokisanGames** [comment]
What's the time frame on that? If it's days, I'll wait. If it's weeks, I'll merge this in and we can look again later.

**Comment by Delsin-Yu** [comment]
> What's the time frame on that?

I think I can finish the works before Sunday ends.

**Comment by Delsin-Yu** [comment]
I think the new generator is ready, with the diagnostics now there are only two spots where things can be improved on my end:


```
[Terrain3D]
Unable to disambiguate the supplied constant definition set [Disabled,Static,Dynamic] to one of the following enum definitions: 
Class<GeometryInstance3D>.GIMode
Class<Light3D>.BakeMode
Class<RenderingServer>.LightBakeMode
in CreatePropertyInfo: gi_mode


[Terrain3DMaterial]
Unable to disambiguate the supplied constant definition set [Linear,Nearest] to one of the following enum definitions: 
Class<RenderingDevice>.SamplerFilter
Class<Terrain3DMaterial>.TextureFiltering
```


But the Godot Engine can link them to their corresponding enum types, so we are good. Enum linking is generally hard for third-party wrapper-type generators like mine, so this should be very easy to implement with your own binding generator.

**Comment by TokisanGames** [comment]
> [Terrain3DMaterial]
> Unable to disambiguate the supplied constant definition set [Linear,Nearest] to one of the following enum definitions: 
> Class<RenderingDevice>.SamplerFilter
> Class<Terrain3DMaterial>.TextureFiltering

This is our own enum. Though we use it to rewrite the shader to change the filtering, it has nothing to do with RenderingDevice.SamplerFilter. It is defined in the same place and way as WorldBackground. But that one didn't get flagged? I don't know what should be different about how we define this. 


> [Terrain3D]
> Unable to disambiguate the supplied constant definition set [Disabled,Static,Dynamic] to one of the following enum definitions: 
> Class<GeometryInstance3D>.GIMode
> Class<Light3D>.BakeMode
> Class<RenderingServer>.LightBakeMode
> in CreatePropertyInfo: gi_mode

This is not our own enum. Nor are we binding the values. terrain_3d.h defines these members with the engine's enums. Does it not flag cast_shadows?
```
RenderingServer::ShadowCastingSetting _cast_shadows = RenderingServer::SHADOW_CASTING_SETTING_ON;
GeometryInstance3D::GIMode _gi_mode = GeometryInstance3D::GI_MODE_STATIC;

ADD_PROPERTY(PropertyInfo(Variant::INT, "gi_mode", PROPERTY_HINT_ENUM, "Disabled,Static,Dynamic"), "set_gi_mode", "get_gi_mode");

void Terrain3D::set_gi_mode(const GeometryInstance3D::GIMode p_gi_mode);

```

Using the gdscript bindings, can you not see that the parameter for set_gi_mode() is using the engine enum GeometryInstance3D::GIMode? Then you don't need to guess at Light3D and RenderingServer.

**Comment by Delsin-Yu** [comment]
> Using the gdscript bindings, can you not see that the parameter for set_gi_mode() is using the engine enum GeometryInstance3D::GIMode

The issue is that ClassDB is the only source from which third-party generators can obtain information, so I'm unable to access the type information for the GD script. However, this is primarily a concern on my end. I don't believe there are any obstacles for Terrain3D at this time. Since you plan to ship your generators, you should be able to handle these enums without difficulty. I will explore what solutions can be implemented for my generators.

**Comment by TokisanGames** [comment]
Alright, I will clean up this PR and merge it in.
